name: DevHabit
services:
# The container for the API
  devhabit.api:
    container_name: DevHabit.API
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - 5000:8080  
      - 5001:8081
    depends_on:
      - devhabit.postgres
    environment:
    # Open Telemetry
      # SEQ
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

# PostgreSQL container as the database to the application
  devhabit.postgres:
    container_name: DevHabit.PostgreSQL
    image: postgres:17.2
    environment:
      POSTGRES_DB: devhabit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
# SEQ container to ingest the Open Telemetry data in dev environments
  devhabit.seq:
    container_name: DevHabit.SEQ
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341 

# Aspire dashboard container to ingest the Open Telemetry data
  devhabit.aspire-dashboard:
    container_name: DevHabit.AspireDashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
      ASPIRE_DASHBOARD_TELEMETRY_OPTOUT: "true"
    ports:
      - 18888:18888
